export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/* *****Chat Actions***** */
export const NEW_MESSAGE = "NEW_MESSAGE";
export const CHANGE_CONVERSATION = "CHANGE_COVERSATION";

export const INIT_CHANNELS = "INIT_CHANNELS";
export const INIT_USERS_CONVO = "INIT_USERS_CONVO";
export const CHAT_LOADING_DONE = "CHAT_LOADING_DONE";
export const DIRECTS_LOADING_DONE = "DIRECTS_LOADING_DONE";